name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
    - uses: actions/checkout@v4
    - name: Install MinGW
      run: sudo apt-get install -y mingw-w64
    - name: Set up Rust toolchain
      run: |
        rustup update ${{ matrix.toolchain }}
        rustup default ${{ matrix.toolchain }}
        rustup target add x86_64-pc-windows-gnu
    - name: Build for Linux (Release)
      run: cargo build --release
    - name: Build for Windows (Release)
      run: cargo build --target x86_64-pc-windows-gnu --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload Linux Release
      uses: actions/upload-artifact@v3
      with:
        name: linux-release
        path: target/release/bw_http_forwarder
    - name: Upload Windows Release
      uses: actions/upload-artifact@v3
      with:
        name: windows-release
        path: target/x86_64-pc-windows-gnu/release/bw_http_forwarder.exe
