name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
    - uses: actions/checkout@v4
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - run: rustup target add x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --verbose
    - name: Windows Build
      run: cargo build --verbose --target x86_64-pc-windows-gnu
    - name: Run tests
      run: cargo test --verbose
