name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
    - uses: actions/checkout@v4
    - name: Install MinGW
      run: sudo apt-get install -y mingw-w64
    - name: Set up Rust toolchain
      run: |
        rustup update ${{ matrix.toolchain }}
        rustup default ${{ matrix.toolchain }}
        rustup target add x86_64-pc-windows-gnu
    - name: Build for Linux (Release)
      run: cargo build --release
    - name: Build for Windows (Release)
      run: cargo build --target x86_64-pc-windows-gnu --release
    - name: Run tests
      run: cargo test --verbose
    - name: Package Release
      run: |
        mkdir release
        cp target/release/bw_http_forwarder release/bw_http_forwarder-v${{ github.sha }}
        cp target/x86_64-pc-windows-gnu/release/bw_http_forwarder.exe release/bw_http_forwarder-v${{ github.sha }}.exe
        cd release
        zip -r bw_http_forwarder-v${{ github.sha }} bw_http_forwarder-v${{ github.sha }}-linux-x86_64.zip
        zip -r bw_http_forwarder-v${{ github.sha }}-windows-x86-64.exe bw_http_forwarder-v${{ github.sha }}-windows-x86-64.zip
        cd ..
    - name: Release Binaries
      uses: softprops/action-gh-release@v1
      with:
        tag: ${{ github.ref }}
